# find Best accuracy

In [1]:
import pandas as pd
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr, spearmanr
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("data_cleaned.csv", header=0)
data

,DEPTH,CALI,DT,NPHI,PHIE,RHOB,SW,litho,VANH,VCLC,VDOL,VOL_SHALE
0,0,0,1,1,2,4,2,0,6,5,0,0
1,0,0,2,2,3,3,1,0,6,5,1,0
2,0,1,2,2,3,3,1,0,6,4,2,0
3,0,1,2,3,4,3,2,1,6,3,3,0
4,0,0,3,3,5,2,2,4,6,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2297,6,1,5,3,6,1,6,2,0,0,0,0
2298,6,2,4,3,6,1,6,2,0,0,0,0
2299,6,2,4,3,6,1,6,2,0,0,0,0
2300,6,2,4,3,5,2,6,2,0,0,0,0
2301,6,2,4,3,5,2,6,2,0,0,1,0

In [3]:
train = data.sample(n=1700, random_state=74)
test = data.drop(train.index)

# Assuming your DataFrame is named 'train' and the target column is named 'target'
X = train.drop('litho', axis=1).values
y = train['litho'].values.reshape(-1, 1)
y = y.ravel()

data.head()

   DEPTH  CALI  DT  NPHI  PHIE  RHOB  SW  litho  VANH  VCLC  VDOL  VOL_SHALE
0      0     0   1     1     2     4   2      0     6     5     0          0
1      0     0   2     2     3     3   1      0     6     5     1          0
2      0     1   2     2     3     3   1      0     6     4     2          0
3      0     1   2     3     4     3   2      1     6     3     3          0
4      0     0   3     3     5     2   2      4     6     1     4          0

In [4]:
import itertools

num_layers = 3
max_neurons = 30

layer_combinations = []
for r in range(1, num_layers + 1):
    layer_combinations += list(itertools.product(range(1, max_neurons + 1), repeat=r))

In [5]:
import warnings
from sklearn.exceptions import ConvergenceWarning
X_test = test.drop('litho', axis=1).values
Y_test = test['litho'].values.reshape(-1, 1)
Y_test = Y_test.ravel()


with warnings.catch_warnings():
    
    warnings.filterwarnings("ignore", category=ConvergenceWarning)
    best_accuracy = 0
    best_arrangement = None

    for arrangement in layer_combinations:
        mlp = MLPClassifier(hidden_layer_sizes=arrangement, random_state=42)

        mlp.fit(X, y)
        
        y_pred = mlp.predict(X_test)

        accuracy = accuracy_score(Y_test, y_pred)
        # if accuracy > 0.80:
            

        if accuracy > best_accuracy:
            print("Arrangement:", arrangement)
            print("Accuracy:", accuracy)
            best_accuracy = accuracy
            best_arrangement = arrangement

    print("Best Arrangement:", best_arrangement)
    print("Best Accuracy:", best_accuracy)

Arrangement: (1,)
Accuracy: 0.7757475083056479
Arrangement: (3,)
Accuracy: 0.813953488372093
Arrangement: (4,)
Accuracy: 0.845514950166113
Arrangement: (5,)
Accuracy: 0.8986710963455149
Arrangement: (9,)
Accuracy: 0.9003322259136213
Arrangement: (13,)
Accuracy: 0.9086378737541528
Arrangement: (29,)
Accuracy: 0.9119601328903655

c:\Users\pars\Desktop\mona\env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:697: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

In [ ]:
# import warnings
# from sklearn.exceptions import ConvergenceWarning




# with warnings.catch_warnings():
    
#     warnings.filterwarnings("ignore", category=ConvergenceWarning)
#     best_accuracy = 0
#     best_arrangement = None

#     for x in range(200):
#         for k in range(200):
#             train = data.sample(n=1700, random_state=k)
#             test = data.drop(train.index)

#             # Assuming your DataFrame is named 'train' and the target column is named 'target'
#             X = train.drop('litho', axis=1).values
#             y = train['litho'].values.reshape(-1, 1)
#             y = y.ravel()

#             data.head()

#             X_test = test.drop('litho', axis=1).values
#             Y_test = test['litho'].values.reshape(-1, 1)
#             Y_test = Y_test.ravel()
#             mlp = MLPClassifier(hidden_layer_sizes=(27,30), random_state=x)

#             mlp.fit(X, y)
            
#             y_pred = mlp.predict(X_test)

#             accuracy = accuracy_score(Y_test, y_pred)
#             # if accuracy > 0.80:
                

#             if accuracy > best_accuracy:
#                 print(f"Arrangement:{x}-{k}" )
#                 print("Accuracy:", accuracy)
#                 best_accuracy = accuracy
#                 best_arrangement = x

#     print("Best Arrangement:", best_arrangement)
#     print("Best Accuracy:", best_accuracy)

Arrangement:0-0
Accuracy: 0.8538205980066446
Arrangement:0-1
Accuracy: 0.8571428571428571
Arrangement:0-7
Accuracy: 0.8588039867109635
Arrangement:0-15
Accuracy: 0.8621262458471761
Arrangement:0-20
Accuracy: 0.8754152823920266
Arrangement:0-22
Accuracy: 0.8853820598006644
Arrangement:0-100
Accuracy: 0.8870431893687708
Arrangement:0-175
Accuracy: 0.8903654485049833

c:\Users\pars\Desktop\mona\env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:697: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")